aws:
  access-key: test
  secret-key: test
  region-name: us-east-1


application:
  bucket:
    name: aws-java-demo


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://my_db_url
    username: test
    password: test

